import pandas as pd
import numpy as np
from typing import Dict, Any, Union, List, Optional
import logging
import traceback
import time
from scipy import stats

from src.utils.indicators import IndicatorUtils
from src.utils.error_handling import handle_calculation_error, handle_indicator_error, validate_input
from src.config.manager import ConfigManager
from .base_indicator import BaseIndicator, IndicatorMetrics
from ..core.logger import Logger
from src.core.analysis.indicator_utils import log_score_contributions, log_component_analysis, log_final_score, log_calculation_details, log_multi_timeframe_analysis
from src.core.formatting.formatter import LogFormatter
from src.core.analysis.indicator_utils import log_final_score
from src.core.analysis.indicator_utils import log_component_analysis
from src.core.analysis.indicator_utils import log_score_contribution_section
from src.core.analysis.indicator_utils import log_multi_timeframe_analysis
from src.core.analysis.indicator_utils import log_indicator_results
from src.core.analysis.indicator_utils import log_timeframe_scores
from src.core.analysis.indicator_utils import log_divergences
from src.core.analysis.indicator_utils import log_score_adjustments
from src.core.analysis.indicator_utils import log_timeframe_score
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe
from src.core.analysis.indicator_utils import log_timeframe_score_with_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe_and_score_and_weight_and_score_and_adjustment_and_symbol_and_timeframe
