#!/usr/bin/env python3
"""
Test script to verify the market report template fix.
"""

import os
import sys
import json
from datetime import datetime

# Add the src directory to the path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from jinja2 import Environment, FileSystemLoader

def create_test_data():
    """Create sample data that matches the actual structure generated by the market reporter."""
    return {
        'timestamp': int(datetime.now().timestamp() * 1000),
        'generated_at': datetime.now().isoformat(),
        'market_overview': {
            'regime': 'BULLISH',
            'trend_strength': '75.5%',
            'total_volume': 1234567890,
            'total_turnover': 9876543210,
            'total_open_interest': 555666777,
            'volatility': 2.45,
            'timestamp': int(datetime.now().timestamp() * 1000)
        },
        'top_performers': {
            'gainers': [
                {'symbol': 'BTCUSDT', 'price': 45000.0, 'change_percent': 5.2, 'volume': 1000000, 'change': '+5.20'},
                {'symbol': 'ETHUSDT', 'price': 3200.0, 'change_percent': 3.8, 'volume': 800000, 'change': '+3.80'},
                {'symbol': 'ADAUSDT', 'price': 0.85, 'change_percent': 2.1, 'volume': 500000, 'change': '+2.10'}
            ],
            'losers': [
                {'symbol': 'DOGEUSDT', 'price': 0.12, 'change_percent': -2.5, 'volume': 300000, 'change': '-2.50'},
                {'symbol': 'XRPUSDT', 'price': 0.55, 'change_percent': -1.8, 'volume': 400000, 'change': '-1.80'}
            ],
            'total_analyzed': 20,
            'failed_symbols': 0,
            'timestamp': int(datetime.now().timestamp() * 1000)
        },
        'futures_premium': {
            'premiums': {
                'BTCUSDT': {
                    'spot_price': 45000.0,
                    'futures_price': 45100.0,
                    'premium': '0.22%',
                    'annualized_yield': '8.5%'
                },
                'ETHUSDT': {
                    'spot_price': 3200.0,
                    'futures_price': 3210.0,
                    'premium': '0.31%',
                    'annualized_yield': '11.2%'
                }
            },
            'timestamp': int(datetime.now().timestamp() * 1000)
        },
        'smart_money_index': {
            'index': 68.5,
            'sentiment': 'BULLISH',
            'signals': ['Large accumulation detected', 'Institutional buying pressure'],
            'timestamp': int(datetime.now().timestamp() * 1000)
        },
        'whale_activity': {
            'whale_activity': {
                'significant_transactions': 15,
                'total_volume': 50000000,
                'net_flow': 'POSITIVE'
            },
            'timestamp': int(datetime.now().timestamp() * 1000)
        },
        'performance_metrics': {
            'metrics': {
                'api_latency': {
                    'avg': 120,
                    'max': 350,
                    'p95': 280
                },
                'error_rate': 0.5,
                'processing_time': 2.3
            },
            'timestamp': int(datetime.now().timestamp() * 1000)
        }
    }

def test_template_rendering():
    """Test that the template renders correctly with the sample data."""
    print("Testing market report template rendering...")
    
    # Set up template environment
    template_dir = os.path.join(os.path.dirname(__file__), '..', 'src', 'templates')
    env = Environment(loader=FileSystemLoader(template_dir))
    
    try:
        template = env.get_template('market_report_dark.html')
        print(f"✓ Template loaded successfully from {template_dir}")
    except Exception as e:
        print(f"✗ Failed to load template: {e}")
        return False
    
    # Create test data
    test_data = create_test_data()
    print("✓ Test data created")
    
    # Render template
    try:
        html_content = template.render(**test_data)
        print("✓ Template rendered successfully")
        
        # Check for "unavailable" messages
        unavailable_count = html_content.count("currently unavailable")
        if unavailable_count == 0:
            print("✓ No 'currently unavailable' messages found - template fix successful!")
        else:
            print(f"✗ Found {unavailable_count} 'currently unavailable' messages - template fix incomplete")
            
            # Find which sections are still showing unavailable
            sections = [
                "Market overview data is currently unavailable",
                "Top performers data is currently unavailable", 
                "Futures premium data is currently unavailable",
                "Smart Money Index data is currently unavailable",
                "Whale activity data is currently unavailable",
                "Performance metrics are currently unavailable"
            ]
            
            for section in sections:
                if section in html_content:
                    print(f"  - {section}")
        
        # Save rendered HTML for inspection
        output_path = os.path.join(os.path.dirname(__file__), 'test_template_output.html')
        with open(output_path, 'w') as f:
            f.write(html_content)
        print(f"✓ Rendered HTML saved to {output_path}")
        
        return unavailable_count == 0
        
    except Exception as e:
        print(f"✗ Template rendering failed: {e}")
        return False

if __name__ == "__main__":
    success = test_template_rendering()
    if success:
        print("\n🎉 Template fix verification PASSED!")
        sys.exit(0)
    else:
        print("\n❌ Template fix verification FAILED!")
        sys.exit(1) 