#!/usr/bin/env python3
"""
Check if interpretations are being captured in confluence analysis
"""
import asyncio
import sys
import os
import json

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.api.cache_adapter_direct import DirectCacheAdapter

async def check_interpretations():
    """Check what's being stored in confluence breakdown cache"""
    print("\n" + "="*60)
    print("🔍 Checking Confluence Interpretations in Cache")
    print("="*60)
    
    adapter = DirectCacheAdapter()
    
    # List of symbols to check
    symbols = ['BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'BNBUSDT']
    
    for symbol in symbols:
        print(f"\n📊 Checking {symbol}:")
        print("-" * 40)
        
        # Check confluence breakdown
        breakdown_key = f'confluence:breakdown:{symbol}'
        breakdown = await adapter._get(breakdown_key, None)
        
        if breakdown and isinstance(breakdown, dict):
            print(f"✅ Found breakdown data for {symbol}")
            
            # Check what fields are present
            fields = list(breakdown.keys())
            print(f"   Fields: {fields}")
            
            # Check for interpretations
            if 'interpretations' in breakdown:
                interpretations = breakdown['interpretations']
                if interpretations:
                    print(f"   ✅ Has interpretations: {type(interpretations)}")
                    if isinstance(interpretations, dict):
                        print(f"      Keys: {list(interpretations.keys())}")
                        # Show sample interpretation
                        for key, value in list(interpretations.items())[:2]:
                            print(f"      {key}: {str(value)[:100]}...")
                    else:
                        print(f"      Content: {str(interpretations)[:200]}...")
                else:
                    print(f"   ⚠️ Interpretations field is empty")
            else:
                print(f"   ❌ No interpretations field")
            
            # Check components
            if 'components' in breakdown:
                print(f"   Components: {list(breakdown['components'].keys()) if isinstance(breakdown['components'], dict) else 'N/A'}")
            
            # Check sub_components
            if 'sub_components' in breakdown:
                print(f"   Sub-components: {list(breakdown['sub_components'].keys())[:5] if isinstance(breakdown['sub_components'], dict) else 'N/A'}...")
                
        else:
            print(f"❌ No breakdown data for {symbol}")
            
            # Check basic confluence key
            basic_key = f'confluence:{symbol}'
            basic_data = await adapter._get(basic_key, None)
            if basic_data:
                print(f"   Found basic confluence data: {type(basic_data)}")
    
    # Check if there's any data in analysis:signals
    print("\n" + "="*60)
    print("📈 Checking Signals for Interpretations")
    print("-" * 40)
    
    signals = await adapter._get('analysis:signals', {})
    if signals and 'signals' in signals:
        signal_list = signals['signals']
        print(f"Found {len(signal_list)} signals")
        
        # Check first signal for interpretations
        if signal_list:
            first_signal = signal_list[0]
            print(f"\nFirst signal ({first_signal.get('symbol', 'N/A')}):")
            if 'interpretations' in first_signal:
                print(f"   ✅ Has interpretations: {first_signal['interpretations']}")
            else:
                print(f"   ❌ No interpretations in signal")
            print(f"   Fields: {list(first_signal.keys())}")
    else:
        print("No signals found in cache")
    
    print("\n" + "="*60)
    print("📝 Summary")
    print("-" * 40)
    print("Interpretations should be captured in:")
    print("1. confluence:breakdown:{symbol} -> 'interpretations' field")
    print("2. Mobile data API includes interpretations from breakdown")
    print("3. Signals may include interpretations if generated")
    print("\nIf interpretations are missing, they need to be:")
    print("- Generated by InterpretationGenerator")
    print("- Stored in confluence breakdown cache")
    print("- Included in API responses")

if __name__ == "__main__":
    asyncio.run(check_interpretations())